markdown: kramdown
Rouge: true
highlighter: rouge
permalink: /blog/:year/:month/:day/:title
name: Sijin LI
url: https://github.com/sijinli
baseurl: /blog_arxiv_2023.github.io

google_analytics: UA-42209870-1
disqus_shortname: sijin

paginate:  3

collections:
  my_categories:
    output: true
    permalink: /blog/category/:name/
  my_tags:
    output: true
    permalink: /blog/tag/:name/

pages_list:       
  About: '/blog_arxiv_2023.github.io/about'
  Posts: '/blog_arxiv_2023.github.io/posts'

gems:
  - jekyll-gist
  - jekyll-sitemap